{% from 'utils/code_block.html' import code_block %}

<h1 id="exceptions">Исключения</h1>
<p>В java есть два класса исключений, наследующихся от класса Throwable:</p>
<ul>
    <li><code>Error</code>: внутренние ошибки в java, на них мы почти не можем повлиять</li>
    <li><code>Exception</code>: сами исключения, который бывают:
        <ol>
            <li>непроверяемыми: наследуются от RuntimeException, не обрабатываются с помощью try catch</li>
            <li>проверяемые: все остальные</li>
        </ol>
    </li>
</ul>

<h1 id="try_catch_finally">Классическая обработка исключений</h1>
<p>Осуществляется блоками try, catch, finally</p>
{{ code_block(try_catch) }}

<h1 id="throw_throws">throw и throws</h1>
<p>С помощью этого оператора мы можем выбросить исключение:</p>
{{ code_block(throw) }}
<p>Однако есть нюанс: в java все выброшенные исключения должны быть обработаны. Поэтому если мы выбрасываем исключение, то мы его должны либо сразу
обработать через catch, либо же в методе, в котором может быть выброшено исключение указать: <code>public void method(Object arg) throws SomeException {}</code></p>
<p>Тогда при использовании этого метода мы будем обязаны либо пробросить исключение дальше, либо обработать его. Таким образом
гарантируется, что все исключения будут обработаны.</p>

<h1 id="try-with-resources">try-with-resources</h1>
<p>при работе с потоками нам нужно их закрывать, особенно если это файл. Для этого мы можем вызвать его метод <code>.close()</code>, предварительно
обработав все возможные исключения.</p>
<p>Но кроме этого мы можем определить поток таким образом:</p>
{{ code_block(tryWithResources) }}
<p>Определенный таким образом поток закроется после выполнения блока try</p>